#!/usr/bin/env bash
# 301 redirection script

apt-get update
apt-get -y install nginx

# Allow HTTP traffic on port 80 through the firewall
sudo ufw allow 'Nginx HTTP'

# Set up web directory and permissions; directory already exists
# but will keep line for idempotency and script reusability for automation on another server
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create a simple HTML file
echo 'Hello World!' > /var/www/html/index.html

# Define Nginx configuration with redirection
# Backslash to mark continuity
# default_server string on both IPV4 and IPV6 signify just one server
CONFIGURE_SERVER=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.htm index.html index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    sed -i '/location \/ {/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n'
}"

# Apply the Nginx configuration
# Where -c tells bash to read and execute the command that follows it as a string
# -e enables interpretation of backslash escapes
bash -c "echo -e '$CONFIGURE_SERVER' > /etc/nginx/sites-enabled/default"

# Start or restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi
