#!/usr/bin/env bash
# sets up a new 404 error page

# Update repositories and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple index.html file with "Hello World!" content
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Create a custom 404.html page with the message "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Define Nginx configuration using a heredoc for clarity
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}" > default

# Apply the Nginx default configuration
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
