#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
hostname=$(hostname)
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo sed -i "/server_name _;/a \\tadd_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo systemctl restart nginx