#!/usr/bin/env bash
# 301 redirection script

# Update repositories and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow HTTP traffic on port 80 through the firewall
sudo ufw allow 'Nginx HTTP'

# Set up web directory and permissions; directory already exists
# but keeping this line for idempotency and script reusability
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www/
sudo chmod -R 755 /var/www/html

# Create a simple HTML file
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Backing up default config
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bk

# Define Nginx configuration with redirection using a heredoc
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Wriiting the 404 Error directive
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_code_404.html
sudo sed -i '25i\	error_page 404 /error_code_404.html;' /etc/nginx/sites-available/default
sudo sed -i '26i\       add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
# Restart nginx
sudo service nginx restart

echo -e "\nRedirection Complete.\n"
