#!/usr/bin/env bash
# Script to display "To infinity and beyond" indefinitely, handle signals, and manage a PID file.

PID_FILE="/var/run/myscript.pid"
clean_up_and_exit() {
    rm -f "$PID_FILE"
    exit 0
}
trap 'echo "I hate the kill command"; clean_up_and_exit' SIGTERM
trap 'clean_up_and_exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
echo $$ > "$PID_FILE"
while true; do
    echo "To infinity and beyond"
    sleep 2
done
