#!/usr/bin/env bash
# Manages the script manage_my_process.

MANAGE_MY_PROCESS="./manage_my_process"
PID_FILE="/var/run/my_process.pid"
start_process() {
    $MANAGE_MY_PROCESS &
    echo $! > $PID_FILE
    echo "manage_my_process started"
}
stop_process() {
    if [ -f $PID_FILE ]; then
        PID=$(cat $PID_FILE)
        kill $PID
        rm $PID_FILE
        echo "manage_my_process stopped"
    else
        echo "PID file not found; manage_my_process is not running"
    fi
}
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}
case $1 in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
