#!/usr/bin/env bash
# Script displays string "Best School" 10 times.

count=0
while [ $count -lt 10 ]
do
    if [ $count == 9 ]
    then
	    echo "Hi"
    fi
    echo "Best School"
    count=$((count+1))
done
