#!/usr/bin/env bash
# Stop the currently running Nginx process
systemctl stop nginx

# Update the Nginx configuration file to run as the nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Start Nginx with the updated configuration
systemctl start nginx